import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Syah Bandi – Fullstack Developer Portfolio",
  description: "Explore the work of Syah Bandi, a passionate Fullstack Engineer building innovative apps using modern web, mobile, and cloud technologies.",
  keywords: [
    "syah bandi",
    "fullstack developer",
    "software engineer",
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "portfolio",
    "web development",
    "mobile development",
    "cloud technologies",
    "3d-portfolio",
    "3d-website",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "tailwindcss",
    "ui/ux",
    "javascript",
    "typescript",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Syah Bandi",
    url: "https://iuno.in",
  },
} as const;