import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Rakit Aplikasi | Space Portfolio",
  description: "Welcome to my full stack Next.js 14 space portfolio.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Rakit Aplikasi",
    url: "https://drive.google.com/drive/folders/13iRdFGYHEI-0Mk8fNTjt_9ckjCvbeAew",
  },
} as const;
